# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = nil
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.date = %q{2010-05-11}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "TODO"
  ]
  s.files = [
    "LICENSE",
     "README",
     "Rakefile",
     "TODO",
     "VERSION",
     "ext/jitextra/Rakefile",
     "ext/jitextra/jitextra.c",
     "ext/jitextra/jitextra.o",
     "ext/jitextra/libjitextra.so",
     "lib/libjit.rb",
     "lib/libjit/context.rb",
     "lib/libjit/control_structures.rb",
     "lib/libjit/errors.rb",
     "lib/libjit/function.rb",
     "lib/libjit/label.rb",
     "lib/libjit/type.rb",
     "lib/libjit/value.rb",
     "lib/libjitextra.so",
     "libjit-ffi.gemspec",
     "spec/bitwise_spec.rb",
     "spec/comparison_spec.rb",
     "spec/constant_spec.rb",
     "spec/context_spec.rb",
     "spec/if_spec.rb",
     "spec/libc_spec.rb",
     "spec/pointer_spec.rb",
     "spec/pointer_type_spec.rb",
     "spec/primitive_type_spec.rb",
     "spec/spec_helper.rb",
     "spec/struct_spec.rb",
     "spec/struct_type_spec.rb",
     "spec/type_spec.rb",
     "spec/value_spec.rb",
     "spec/void_type_spec.rb",
     "spec/while_spec.rb"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = nil
  s.test_files = [
    "spec/value_spec.rb",
     "spec/context_spec.rb",
     "spec/libc_spec.rb",
     "spec/void_type_spec.rb",
     "spec/pointer_type_spec.rb",
     "spec/struct_spec.rb",
     "spec/bitwise_spec.rb",
     "spec/if_spec.rb",
     "spec/type_spec.rb",
     "spec/while_spec.rb",
     "spec/constant_spec.rb",
     "spec/pointer_spec.rb",
     "spec/spec_helper.rb",
     "spec/struct_type_spec.rb",
     "spec/primitive_type_spec.rb",
     "spec/comparison_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

